<?php

declare(strict_types=1);

namespace Symfinity\FontManager\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    /**
     * @psalm-suppress UndefinedInterfaceMethod
     * @psalm-suppress PossiblyNullReference
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('font_manager');
        /** @var ArrayNodeDefinition $root */
        $root = $treeBuilder->getRootNode();

        // @phpstan-ignore-next-line - Fluent interface methods are not fully recognized by PHPStan
        $root
            ->children()
                ->scalarNode('default_provider')
                    ->defaultValue('google')
                    ->info('Default font provider: google, bunny, or local')
                ->end()
                ->integerNode('cache_ttl')
                    ->defaultValue(3600)
                    ->info('API response cache TTL in seconds (default: 3600 = 1 hour)')
                ->end()
                ->booleanNode('use_locked_fonts')
                    ->defaultFalse()
                    ->info('Use locked/local fonts in production instead of CDN')
                ->end()
                ->scalarNode('fonts_dir')
                    ->defaultValue('%kernel.project_dir%/assets/fonts')
                    ->info('Directory where locked fonts are stored (served by AssetMapper)')
                ->end()
                ->scalarNode('manifest_file')
                    ->defaultValue('%kernel.project_dir%/var/font-manager.lock.json')
                    ->info('Path to the fonts manifest file')
                ->end()
                ->arrayNode('unicode_subsets')
                    ->info('Unicode subsets to include when downloading fonts (reduces file count)')
                    ->scalarPrototype()->end()
                    ->defaultValue(['latin', 'latin-ext'])
                    ->example(['latin', 'latin-ext', 'cyrillic'])
                ->end()
                ->arrayNode('providers')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('google')
                            ->canBeEnabled()
                            ->children()
                                ->scalarNode('api_key')
                                    ->defaultNull()
                                    ->info('Google Fonts API key (optional, for search command)')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('bunny')
                            ->canBeEnabled()
                        ->end()
                        ->arrayNode('fontsource')
                            ->canBeEnabled()
                        ->end()
                        ->arrayNode('local')
                            ->canBeDisabled()
                            ->children()
                                ->scalarNode('directory')
                                    ->defaultValue('%kernel.project_dir%/assets/fonts/custom')
                                    ->info('Directory for custom local fonts')
                                ->end()
                                ->arrayNode('fonts')
                                    ->arrayPrototype()
                                        ->children()
                                            ->scalarNode('display_name')->end()
                                            ->scalarNode('category')->end()
                                            ->arrayNode('weights')
                                                ->integerPrototype()->end()
                                            ->end()
                                            ->arrayNode('styles')
                                                ->scalarPrototype()->end()
                                            ->end()
                                            ->arrayNode('files')
                                                ->scalarPrototype()->end()
                                            ->end()
                                            ->scalarNode('unicode_range')->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('build')
                    ->addDefaultsIfNotSet()
                    ->info('Build tool configuration')
                    ->children()
                        ->scalarNode('tool')
                            ->defaultValue('auto')
                            ->info('Build tool: auto (detect), assetmapper, webpack, or vite')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('export')
                    ->addDefaultsIfNotSet()
                    ->info('Export format configuration')
                    ->children()
                        ->booleanNode('auto_detect')
                            ->defaultFalse()
                            ->info('Auto-detect required formats based on project setup')
                        ->end()
                        ->arrayNode('formats')
                            ->info('Enabled export formats')
                            ->scalarPrototype()->end()
                            ->defaultValue(['css_variables'])
                            ->example(['css_variables', 'scss_bootstrap', 'tailwind_config', 'typescript_definitions'])
                        ->end()
                        ->arrayNode('output')
                            ->addDefaultsIfNotSet()
                            ->info('Output path configuration (auto = based on build tool)')
                            ->children()
                                ->scalarNode('base_dir')
                                    ->defaultValue('%kernel.project_dir%')
                                    ->info('Base directory for exports')
                                ->end()
                                ->scalarNode('fonts_dir')
                                    ->defaultValue('auto')
                                    ->info('Fonts directory (auto = based on build tool)')
                                ->end()
                                ->scalarNode('styles_dir')
                                    ->defaultValue('auto')
                                    ->info('Styles directory (auto = based on build tool)')
                                ->end()
                                ->scalarNode('config_dir')
                                    ->defaultValue('auto')
                                    ->info('Config directory (auto = based on build tool)')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('performance')
                    ->addDefaultsIfNotSet()
                    ->info('Performance optimization settings')
                    ->children()
                        ->booleanNode('resource_hints')
                            ->defaultTrue()
                            ->info('Generate resource hints (preconnect, dns-prefetch) for font providers')
                        ->end()
                        ->booleanNode('preload_critical_fonts')
                            ->defaultFalse()
                            ->info('Preload critical font files for above-the-fold content')
                        ->end()
                        ->booleanNode('font_loading_api')
                            ->defaultFalse()
                            ->info('Use Font Loading API for async font loading')
                        ->end()
                        ->booleanNode('prefer_variable_fonts')
                            ->defaultTrue()
                            ->info('Prefer variable fonts over static fonts when available')
                        ->end()
                        ->booleanNode('intelligent_fallbacks')
                            ->defaultTrue()
                            ->info('Generate intelligent font fallback chains based on font metrics')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
