font_manager:
    default_provider: google
    unicode_subsets: ['latin', 'latin-ext']
    cache_ttl: 3600
    use_locked_fonts: false
    fonts_dir: '%kernel.project_dir%/assets/fonts'
    manifest_file: '%kernel.project_dir%/var/font-manager.lock.json'
    export:
        formats:
            - css_variables
    providers:
        google:
            enabled: true
        bunny:
            enabled: false
        fontsource:
            enabled: false
        local:
            enabled: false

when@prod:
    font_manager:
        use_locked_fonts: true
