<?php

declare(strict_types=1);

namespace Symfinity\FontManager\Exporter;

use Symfinity\FontManager\Enum\BuildToolType;

abstract class AbstractExporter implements ExporterInterface
{
    public function getOutputPath(string $baseDir, BuildToolType $buildTool): string
    {
        $subDir = match ($buildTool) {
            BuildToolType::ASSET_MAPPER => 'assets/styles',
            BuildToolType::WEBPACK, BuildToolType::VITE => 'assets',
            default => 'assets',
        };

        return sprintf(
            '%s/%s/%s%s',
            rtrim($baseDir, '/'),
            $subDir,
            $this->getDefaultFilename(),
            $this->getFileExtension()
        );
    }

    public function supportsBuildTool(BuildToolType $buildTool): bool
    {
        // Most exporters support all build tools
        return true;
    }

    public function getDependencies(): array
    {
        return [];
    }

    protected function generateHeader(string $format): string
    {
        $date = date('Y-m-d H:i:s');

        return match ($format) {
            'css', 'scss' => <<<CSS
/**
 * Auto-generated by font-manager
 * Generated: {$date}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next font:lock
 */

CSS,
            'js', 'ts' => <<<JS
/**
 * Auto-generated by font-manager
 * Generated: {$date}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten on next font:lock
 */

JS,
            'json' => '',  // JSON doesn't support comments
            default => '',
        };
    }

    protected function getWeightName(int $weight): string
    {
        return match ($weight) {
            100 => 'thin',
            200 => 'extralight',
            300 => 'light',
            400 => 'normal',
            500 => 'medium',
            600 => 'semibold',
            700 => 'bold',
            800 => 'extrabold',
            900 => 'black',
            default => (string) $weight,
        };
    }
}
