<?php

declare(strict_types=1);

namespace Symfinity\FontManager\Tests\Exporter\Css;

use Symfinity\FontManager\Exporter\Css\CssVariablesExporter;
use Symfinity\FontManager\Model\Font;
use Symfinity\FontManager\Model\FontCollection;
use PHPUnit\Framework\TestCase;

final class CssVariablesExporterTest extends TestCase
{
    private CssVariablesExporter $exporter;

    protected function setUp(): void
    {
        $this->exporter = new CssVariablesExporter();
    }

    public function testGetName(): void
    {
        $this->assertSame('css_variables', $this->exporter->getName());
    }

    public function testGetLabel(): void
    {
        $this->assertSame('CSS Custom Properties', $this->exporter->getLabel());
    }

    public function testGetFileExtension(): void
    {
        $this->assertSame('.css', $this->exporter->getFileExtension());
    }

    public function testExportSingleFont(): void
    {
        $font = new Font(
            name: 'Ubuntu',
            weights: [400, 700],
            styles: ['normal', 'italic'],
            monospace: false,
            semantic: 'sans'
        );

        $collection = new FontCollection([$font]);
        $output = $this->exporter->export($collection);

        $this->assertStringContainsString(':root {', $output);
        $this->assertStringContainsString('--font-family-ubuntu:', $output);
        $this->assertStringContainsString("'Ubuntu', sans-serif", $output);
        $this->assertStringContainsString('--font-family-sans:', $output);
        $this->assertStringContainsString('--font-weight-normal: 400', $output);
        $this->assertStringContainsString('--font-weight-bold: 700', $output);
    }

    public function testExportMultipleFonts(): void
    {
        $fonts = [
            new Font('Ubuntu', [400, 700], ['normal'], false, 'sans'),
            new Font('JetBrains Mono', [400, 500], ['normal'], true, 'mono'),
        ];

        $collection = new FontCollection($fonts);
        $output = $this->exporter->export($collection);

        $this->assertStringContainsString('--font-family-ubuntu:', $output);
        $this->assertStringContainsString('--font-family-jetbrains-mono:', $output);
        $this->assertStringContainsString('--font-family-sans:', $output);
        $this->assertStringContainsString('--font-family-mono:', $output);
    }

    public function testExportIncludesHeader(): void
    {
        $font = new Font('Ubuntu', [400], ['normal'], false, 'sans');
        $collection = new FontCollection([$font]);
        $output = $this->exporter->export($collection);

        $this->assertStringContainsString('Auto-generated by font-manager', $output);
        $this->assertStringContainsString('DO NOT EDIT THIS FILE MANUALLY', $output);
    }

    public function testUsageInstructions(): void
    {
        $instructions = $this->exporter->getUsageInstructions();

        $this->assertStringContainsString('Import in your CSS', $instructions);
        $this->assertStringContainsString('var(--font-family-sans)', $instructions);
    }
}
